### ISSUE TITLE
Packages are NOT existent in raspbian archive

### ISSUE THREAD

**Issue by OtakuWally** [piface/pifacecad#15]
The packages for pifacecad are simple NOT there anymore. Furthermore I would like to see jessie being supported.

**Comment by OtakuWally** [comment]
This is just the kind of support why the piFace products are a NO-GO at the moment!

**Comment by pedromorgan** [comment]
@OtakuWally indeed.. do seem unsupported.. ;-))

**Comment by OtakuWally** [comment]
My /etc/apt/sources.list:
'''
deb http://ftp.debian.org/debian jessie main contrib non-free
deb http://security.debian.org/ jessie/updates main contrib non-free
deb http://ftp.debian.org/debian jessie-updates main contrib non-free

# Special kernel and firmware for the Raspi2
deb https://repositories.collabora.co.uk/debian/ jessie rpi2 

# Raspbian needed for piFaceCAD ONLY!
deb http://archive.raspbian.org/raspbian jessie main contrib non-free
deb-src http://archive.raspbian.org/raspbian jessie main contrib non-free
deb-src http://archive.raspbian.org/raspbian wheezy main contrib non-free
'''

And the apt output:

'''
apt-cache showpkg python3-pifacecad
N: Unable to locate package python3-pifacecad
'''

So please tell me what I am doing wrong, if I am forgetting something. I really would like to avould building from github ... Thanks

**Comment by OtakuWally** [comment]
Of course I tried to install the source package with apt-src as well, which did not work.

**Comment by OtakuWally** [comment]
Well, this is what I found about this topic in a post on StackExchange:

http://raspberrypi.stackexchange.com/questions/14116/how-do-i-install-the-piface-control-display

**Comment by tompreston** [comment]
We're working with the repo maintainers on getting the packages into Jessie as soon as we can. I don't know why they have disappeared. The debs are [here](https://github.com/piface/pifacecad/releases) if you want to install them with `dpkg -i` but you'll have to do dependency resolution yourself.

https://github.com/piface/pifacecommon
https://github.com/tompreston/python-lirc

**Comment by OtakuWally** [comment]
This worked flawlessly. A pointer to the releases on GitHub in the installation guide would be great though, for all people who do not use github that much ;-)

Thanks, at last I can start playing with it ...

**Comment by tompreston** [comment]
@OtakuWally Sure, I'll point to the debs in the docs. Also, Raspbian doesn't officially support Jessie at the moment so neither do we. On top of this you're mixing all kinds of repositories in your `sources.list`. Perhaps try using just:

    deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi

**Comment by OtakuWally** [comment]
Yeah, thanks. I know about the multiple repositories, which actually have been commented out. Just used these to try to get the source package.

**Comment by OtakuWally** [comment]
Since I am using original debian on my RPI2 I see no point in using the raspbian archives as long as you do not support jessie anyways.
