### ISSUE TITLE
Where is the Schematic?

### ISSUE THREAD

**Issue by mf0hka** [piface/pifacecad#18]
Yes, I can figure out what pins are being used, from the library, or by hooking up my scope. But I would rather have a nice schematic. Where is it please? Am I missing it?

**Comment by tompreston** [comment]
We haven't released schematics. Although, this page might help you: http://www.element14.com/community/people/Problemchild/blog/2013/12/25/piface-control-display-tear-down

**Comment by pedromorgan** [comment]
Prefer to keep this open until its confirmed ti works like.. ;-))
