### ISSUE TITLE
sysinfo.py broken in Stretch

### ISSUE THREAD

**Issue by Trotter73** [piface/pifacecad#27]
Hi,

The example sysinfo.py is broken on stretch, it looks like the format of the command "free" has changed and this is breaking the script.

This is thrown back at me.

Traceback (most recent call last):
  File "/usr/share/doc/python3-pifacecad/examples/sysinfo.py", line 75, in <module>
    show_sysinfo()
  File "/usr/share/doc/python3-pifacecad/examples/sysinfo.py", line 56, in show_sysinfo
    cad.lcd.write(":{}".format(get_my_free_mem()))
  File "/usr/share/doc/python3-pifacecad/examples/sysinfo.py", line 35, in get_my_free_mem
    used_mem = float(run_cmd(USED_MEM_CMD))
ValueError: could not convert string to float:

Regards,

**Comment by gbmorrison** [comment]
Hi,

I have fixed in this way - replaced the string after grep with 'Mem'.  The grep command was not finding the right line in the output of free for awk to select from.

USED_MEM_CMD = "free | grep 'Mem' | awk '{print $3}'"

regards,

**Comment by tompreston** [comment]
Maybe we should use a more consistent interface such as `/proc/meminfo` which is what free uses.

- [man proc](http://man7.org/linux/man-pages/man5/proc.5.html)
